# Generated by Django 3.1.12 on 2022-01-24 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0003_auto_20210927_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.ManyToManyField(blank=True, default='SOME STRING', help_text='Media can be part of one or more categories', to='files.Category'),
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='A unique identifier for the Media', unique=True)),
                ('picture', models.FileField(upload_to=files.models.original_media_file_path)),
                ('user', models.ForeignKey(help_text='user that uploads the media', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
